In [1]:
import numpy as np

In [2]:
#creating array
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [3]:
#2D array
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#special arrays
print(np.zeros((3, 3)))
print(np.ones((2, 4)))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#Array Attributes
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)

Shape: (2, 3)
Dimensions: 2
Size: 6


In [6]:
#Array Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


In [7]:
#Sum and Mean
arr = np.array([1, 2, 3, 4])

print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())

Sum: 10
Mean: 2.5
Max: 4
Min: 1


In [8]:
#Indexing and Slicing
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[1:4])

10
[20 30 40]


In [9]:
#Reshape
arr = np.arange(6)

print(arr)
print(arr.reshape(2, 3))


[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [10]:
#Broadcasting
a = np.array([1, 2, 3])

print(a + 5)

[6 7 8]


In [11]:
# Save to a file
np.save('array.npy', arr)


In [12]:
loaded_arr = np.load('array.npy')
print(loaded_arr)

[0 1 2 3 4 5]
